# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build&Test

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!main'   # excludes main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Aranzadi.DocumentAnalysis.Messaging.sln'
      NUGET_FEED_NAME: 'SWF_Burgos_Spain_Artifacts_feed'
      NUGET_FEED_SOURCE: ${{secrets.SOURCE_ARANZADI_NUGET}}
      NUGET_FEED_API_KEY: ${{secrets.APIKEY_ARANZADI_NUGET}}
      PASSWORD_ADO: ${{secrets.PASSWORD_ADO}}
      NUGET_CONFIG: './Nuget.Config'

    name: Build and Test
    runs-on: windows-latest
    strategy:
      matrix:
        nuget: [5.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 2.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: ${{ matrix.nuget }}

    - name: Auth Nuget TR
      run: 
        dotnet nuget add source 'https://pkgs.dev.azure.com/TR-Legal-OnlineServices/_packaging/SWF_Burgos_Spain_Artifacts_feed/nuget/v3/index.json' --name ${{ env.NUGET_FEED_NAME }} --username 'david.sanchezfuentes@thomsonreuters.com' --password 't6cklmze2tgwyigmlhms2s52l26pdnm5sgwwfq4ob73awcqkvuqa' --store-password-in-clear-text --configfile ${{ env.NUGET_CONFIG }}

    - name: Prueba
      run: type ./nuget.config

    - name: Restore Nuget Packages
      run: dotnet restore ${{ env.SOLUTION }} --verbosity detailed  

    - name: Build
      run: dotnet build ${{ env.SOLUTION }}  --no-restore

    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal