name: Release

on:
  push:
    branches:
      - main

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Unit Test
    uses: DavidSanchezTR/POC_DocumentAnalysis.Messaging/.github/workflows/dotnet-build-test.yml@main    
    permissions:
        contents: read
        issues: read
        checks: write
        pull-requests: write
        
  build:

    env:
     configuration: 'Release'
     solution_path: 'Aranzadi.DocumentAnalysis.Messaging.sln'
     nuget_feed_name: 'SWF_Burgos_Spain_Artifacts_feed'
     nuget_feed_source: 'https://pkgs.dev.azure.com/TR-Legal-OnlineServices/_packaging/SWF_Burgos_Spain_Artifacts_feed/nuget/v3/index.json'
     nuget_api_key: ${{ secrets.APIKEY_ARANZADI_NUGET }}
     password_ado: ${{ secrets.PASSWORD_ADO }}
     nuget_config: './Nuget.Config'

    name: Build and Pack   
    runs-on: windows-latest  # For a list of available runner types, refer to  https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    needs: [test]
    strategy:
        matrix:
          nuget_version: [5.x]
          dotnet_version: [6.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: ${{ matrix.dotnet_version }}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
       nuget-version: ${{ matrix.nuget_version }}

    - name: Auth Nuget TR
      run: dotnet nuget add source ${{ env.nuget_feed_source }} --name ${{ env.nuget_feed_name }} --username 'david.sanchezfuentes@thomsonreuters.com' --password ${{ env.password_ado }} --store-password-in-clear-text --configfile ${{ env.nuget_config }}

    - name: Restore Nuget Packages
      run: dotnet restore ${{ env.solution_path }} --verbosity normal 

    - name: Build Solution
      run: dotnet build ${{ env.solution_path }} --configuration ${{ env.configuration }} --no-restore
    
    - name: Build NuGet Package
      run: dotnet pack --configuration ${{ env.configuration }} --output _tmp
      #working-directory: ./Aranzadi.DocumentAnalysis.Messaging

    - name: Upload NuGet package
      uses: actions/upload-artifact@v2
      with:
        name: nuget-package
        path: _tmp/*.nupkg