name: Release

on:
  push:
    branches:
      - main

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  configuration: 'Release'
  solution_path: 'Aranzadi.DocumentAnalysis.Messaging.sln'
  project: './Aranzadi.DocumentAnalysis.Messaging'
  nuget_feed_name: 'SWF_Burgos_Spain_Artifacts_feed'
  nuget_feed_source: 'https://pkgs.dev.azure.com/TR-Legal-OnlineServices/_packaging/SWF_Burgos_Spain_Artifacts_feed/nuget/v3/index.json'
  nuget_api_key: ${{ secrets.APIKEY_ARANZADI_NUGET }}
  password_ado: ${{ secrets.PASSWORD_ADO }}
  nuget_config: './Nuget.Config'

jobs:
#   test:
#     name: Unit Test
#     uses: DavidSanchezTR/POC_DocumentAnalysis.Messaging/.github/workflows/dotnet-build-test.yml@main    
#     permissions:
#         contents: read
#         issues: read
#         checks: write
#         pull-requests: write
        
  build:

    name: Build and Nuget Pack   
    runs-on: windows-latest  # For a list of available runner types, refer to  https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    # needs: [test]
    strategy:
        matrix:
          nuget_version: [5.x]
          dotnet_version: [6.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: ${{ matrix.dotnet_version }}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
       nuget-version: ${{ matrix.nuget_version }}

    - name: Auth Nuget TR
      run: dotnet nuget add source ${{ env.nuget_feed_source }} --name ${{ env.nuget_feed_name }} --username 'david.sanchezfuentes@thomsonreuters.com' --password ${{ env.password_ado }} --store-password-in-clear-text --configfile ${{ env.nuget_config }}

    - name: Restore Nuget Packages
      run: dotnet restore ${{ env.solution_path }} --verbosity normal 

    - name: Build Solution
      run: dotnet build ${{ env.solution_path }} --configuration ${{ env.configuration }} --no-restore
    
    - name: Build NuGet Package
      run: dotnet pack ${{ env.project }} --configuration ${{ env.configuration }} --output _tmp

    - name: Create Artifact NuGet Package
      uses: actions/upload-artifact@v3
      with:
        name: nuget-package
        path: _tmp/*.nupkg

  release:
    # environment:
    #     name: production
    #     url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.tag_version.outputs.new_tag }}
    name: Semantic Release and Nuget Push TR
    needs: [build]

    runs-on: ubuntu-latest
    steps:
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "🚀 release"
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          env:
          GITHUB_TOKEN: ${{ github.token }}
      
    #   - name: Push Nuget Package to NuGet
    #     run: nuget push _tmp/*.nupkg -k ${{ env.nuget_api_key }} -s ${{ env.nuget_feed_source }}